services:

  db:
    image: postgres:16
    container_name: lacrei-postgres-prod
    env_file:
      - .env.prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  web:
    build: .
    container_name: lacrei-api-prod
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    environment:
      DB_HOST: db
    depends_on:
      - db

volumes:
  postgres_data_prod: