name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: lacrei_db
          POSTGRES_USER: lacrei_user
          POSTGRES_PASSWORD: lacrei_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U lacrei_user -d lacrei_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar dependências
        run: poetry install

      - name: Executar Ruff
        run: poetry run ruff check .


      - name: Executar testes
        env:
          SECRET_KEY: chave-teste
          DEBUG: 'False'
          DB_NAME: lacrei_db
          DB_USER: lacrei_user
          DB_PASSWORD: lacrei_password
          DB_HOST: localhost
          DB_PORT: 5432
        run: poetry run python manage.py test

      - name: Construir imagem Docker
        run: docker build -t lacrei-api .